baseURL = "https://alexriss.github.io/Tour-de-Code/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Tour de Code - Bite-sized code snacks"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true


# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "solarized-dark"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true  # allow html

[params]
baseURL = "https://alexriss.github.io/Tour-de-Code/"
title = "Tour de Code"
author = "Tour de Code"
description = "Bite-sized code snacks"
#copyright = "2020-2021"
profilePicture = "images/profile.png"
keywords = ""
favicon = "favicons/"
customCss = ["css/extra.css"]
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true

staticDir = ["static"]

# Google Analytics
gtagId = "G-8YWH8FH629"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/alexriss"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/00alexx"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/alexander-riss-944b8611"


# Comments
[params.utterances]
repo = "alexriss/Tour-de-Code"
issueTerm = "pathname"
theme= "preferred-color-scheme"
# label = 

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
